name: Build Addressables

on:
  workflow_dispatch:

concurrency:
  group: build-addressables-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-addressables:
    uses: ./.github/workflows/unity-ci-reusable.yml
    secrets: inherit
    with:
      build_webgl: false
      build_addressables: true
      deploy_webgl: false
      upload_addressables: true
